/*
 * Clase creada para trabajar con las localidades en la ficha del cliente
 */
package forms.turnos;

import datos.Especialidades;
import datos.Profesionales;
import datos.Profesionales_Especialidades;
import entidades.Especialidad;
import entidades.Profesional;
import entidades.ProfesionalEspecialidad;
import java.util.ArrayList;
import java.util.TreeMap;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author pablo
 */
public class pnlComboProfesionales extends javax.swing.JPanel {

    private TreeMap<Integer, Profesional> listprof;
    private TreeMap<Integer, Especialidad> listesp;
    private TreeMap<Integer, ProfesionalEspecialidad> listprofesp;
    private DefaultComboBoxModel modeloCombo;
    
    private int idEsp;// ID de la especialidad seleccionada

    /**
     * Creates new form pnlComboLocations
     */
    public pnlComboProfesionales() {
        initComponents();
        _loadProfesionales();
    }
    
    //lista de especialidades de los profesionales
    private void _loadProfEsp() {
        ArrayList<ProfesionalEspecialidad> list = new ArrayList<ProfesionalEspecialidad>();
        Profesionales_Especialidades cnx = new Profesionales_Especialidades();
        if (cnx.isOkConexion()) {
            list = cnx.list("SELECT * FROM " + cnx.getTabla());
            cnx.isCloseConexion();
        }
        listprofesp = new TreeMap<Integer, ProfesionalEspecialidad>();
        for (int index = 0; index < list.size(); index++) {
            ProfesionalEspecialidad profesp = list.get(index);
            listprofesp.put(index, profesp);
        }
    }

    
    
    private void _loadProfesionales() {
        ArrayList<Profesional> list = new ArrayList<Profesional>();
        Profesionales cnx = new Profesionales();
        if (cnx.isOkConexion()) {
            list = cnx.list("SELECT * FROM " + cnx.getTabla());
            cnx.isCloseConexion();
        }
        listprof = new TreeMap<Integer, Profesional>();
        modeloCombo = new DefaultComboBoxModel<String>();
        this.jComboBoxProf.setModel(modeloCombo);
        modeloCombo.addElement("Seleccionar...");
        for (int index = 0; index < list.size(); index++) {
            Profesional prof = list.get(index);
            modeloCombo.addElement(prof.getApellido().trim() + ", " + prof.getNombre().trim());
            listprof.put(index, prof);
        }
    }

    public Profesional _getProfesionalSelected() {
        return listprof.get(jComboBoxProf.getSelectedIndex());
    }
    public void _setProfesionalSelected(int idProf) {
        int indexSelectedCombo = -1;
        for (int index = 0; index < listprof.size(); index++) {
            Profesional prof = listprof.get(index);
            if (prof.getId() == idProf) {
                indexSelectedCombo = index;
            }
        }
        jComboBoxProf.setSelectedIndex(indexSelectedCombo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxProf = new javax.swing.JComboBox<>();

        jComboBoxProf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBoxProf, 0, 359, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jComboBoxProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxProf;
    // End of variables declaration//GEN-END:variables
}
