/*
 * Clase creada para trabajar con las localidades en la ficha del cliente
 */
package forms.turnos;

import datos.Especialidades;
import entidades.Especialidad;
import java.util.ArrayList;
import java.util.TreeMap;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author pablo
 */
public class pnlComboEspecialidades extends javax.swing.JPanel {

    private TreeMap<Integer, Especialidad> listesp;
    private DefaultComboBoxModel modeloCombo;
    
    /**
     * Creates new form pnlComboLocations
     */
    public pnlComboEspecialidades() {
        initComponents();
        _loadEspecialidades();
    }
    
    private void _loadEspecialidades(){
        ArrayList<Especialidad> list = new ArrayList<Especialidad>();
        Especialidades cnx = new Especialidades();
        if(cnx.isOkConexion()){
            list = cnx.list("SELECT * FROM " + cnx.getTabla());
            cnx.isCloseConexion();
        }
        listesp = new TreeMap<Integer, Especialidad>();
        modeloCombo = new DefaultComboBoxModel<String>();
        this.jComboBox.setModel(modeloCombo);
        
        modeloCombo.addElement("Seleccionar...");
        for(int index=0;index<list.size();index++){
            Especialidad esp = list.get(index);
            modeloCombo.addElement(esp.getDescripcion().trim());
            listesp.put(index, esp);
        }
    }
    
    
    
    public Especialidad _getEspecialidadSelected(){
        return listesp.get(jComboBox.getSelectedIndex());
    }
    
    public void _setEspecialidadSelected(int idEsp){
        int indexSelectedCombo = -1;
        for(int index=0;index<listesp.size();index++){
            Especialidad esp = listesp.get(index);
            if(esp.getId()==idEsp){
                indexSelectedCombo = index;
            }
        }
        jComboBox.setSelectedIndex(indexSelectedCombo);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox = new javax.swing.JComboBox<>();

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox, 0, 359, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox;
    // End of variables declaration//GEN-END:variables
}
