/*
 * Clase creada para trabajar con las localidades en la ficha del cliente
 */
package forms.turnos;

import datos.ObrasSociales;
import entidades.ObraSocial;
import java.util.ArrayList;
import java.util.TreeMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author pablo
 */
public class pnlComboObrasSociales extends javax.swing.JPanel {

    private TreeMap<Integer, ObraSocial> listObras;
    private DefaultComboBoxModel modeloCombo;
    
    /**
     * Creates new form pnlComboLocations
     */
    public pnlComboObrasSociales() {
        initComponents();
        _loadObrasSociales();
    }
    
    private void _loadObrasSociales(){
        ArrayList<ObraSocial> list = new ArrayList<ObraSocial>();
        ObrasSociales cnx = new ObrasSociales();
        if(cnx.isOkConexion()){
            list = cnx.list("SELECT * FROM " + cnx.getTabla());
            cnx.isCloseConexion();
        }
        listObras = new TreeMap<Integer, ObraSocial>();
        modeloCombo = new DefaultComboBoxModel<String>();
        this.jComboBoxObras.setModel(modeloCombo);
        
        modeloCombo.addElement("Seleccionar...");
        for(int index=0;index<list.size();index++){
            ObraSocial obra = list.get(index);
            modeloCombo.addElement(obra.getDescripcion().trim());
            listObras.put(index, obra);
        }
        
    }
    
    public ObraSocial _getObraSelected(){
        return listObras.get(jComboBoxObras.getSelectedIndex());
    }
    
    public void _setObraSelected(int idObra){
        int indexSelectedCombo = -1;
        for(int index=0;index<listObras.size();index++){
            ObraSocial obra = listObras.get(index);
            if(obra.getId()==idObra){
                indexSelectedCombo = index;
            }
        }
        jComboBoxObras.setSelectedIndex(indexSelectedCombo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxObras = new javax.swing.JComboBox<>();

        jComboBoxObras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBoxObras, 0, 359, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jComboBoxObras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxObras;
    // End of variables declaration//GEN-END:variables
}
