
package forms.Profesional;

import java.beans.PropertyVetoException;
import miselaneos.FrmIntern;
import miselaneos.GUI;

/**
 *
 * @author cesar
 */
public class FrmProfesional extends FrmIntern {
    
    public static int id = 17;
    private int id_prof;// ID del Profesional
    private GUI gui;
    
    /**
     * Creates new form FrmPersonal
     */
    public FrmProfesional() {
        gui = new GUI();
        initComponents();
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException e) {
            e.printStackTrace();
        }
    }
    
    //metodo que recibe el id del profesional desde el login
    public void setIdProf(int id){
        this.id_prof = id;
    }
    
    private void _loadTurnosProfesional(int idprof) {
        gui.loadTurnosProfesional(FrmTurnosProfesional.id, true, idprof);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBarButtons = new javax.swing.JToolBar();
        btnTurno = new botones.BtnTurno();
        jDesktopIntern1 = new miselaneos.JDesktopIntern();

        setTitle("Profesional");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jToolBarButtons.setForeground(new java.awt.Color(153, 153, 153));
        jToolBarButtons.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBarButtons.setAlignmentY(0.3F);
        jToolBarButtons.setBorderPainted(false);

        btnTurno.setText("Listado De Turnos");
        btnTurno.setAlignmentX(0.5F);
        btnTurno.setFocusable(false);
        btnTurno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTurno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnoActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnTurno);

        getContentPane().add(jToolBarButtons);
        getContentPane().add(jDesktopIntern1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnoActionPerformed
        _loadTurnosProfesional(id_prof);
    }//GEN-LAST:event_btnTurnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private botones.BtnTurno btnTurno;
    private miselaneos.JDesktopIntern jDesktopIntern1;
    private javax.swing.JToolBar jToolBarButtons;
    // End of variables declaration//GEN-END:variables
}
