package forms.admin;

import forms.Profesionales.FrmProfesionales;
import forms.cargos.FrmCargos;
import forms.especialidades.FrmEspecialidades;
import forms.horarios.FrmHorarios;
import forms.obrasocial.FrmObraSocial;
import forms.pacientes.FrmPacientes;
import forms.personales.FrmPersonales;
import forms.prof_esp.FrmProfEsp;
import forms.settings.FrmSetting;
import forms.turnos.FrmTurnos;
import java.beans.PropertyVetoException;
import miselaneos.Fecha;
import miselaneos.FrmIntern;
import miselaneos.GUI;
import miselaneos.Iconos;
import miselaneos.Imagenes;

/**
 * @author OBREGON
 */
public class FrmPanelAdmin extends FrmIntern {

    public static int id = 6;
    public static Iconos iconos = new Iconos();//Declaro public y static para poder acceder luego desde cualquier lugar del proyecto en cualquier objeto
    public static Imagenes imgs = new Imagenes(); //Misma situacion que Iconos
    public static Fecha fe = new Fecha(); //Misma situacion que Iconos
    private GUI gui;

    public FrmPanelAdmin() {
        initComponents();
        gui = new GUI();
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException e) {
            e.printStackTrace();
        }
    }

    //metodos para cargar el FrmIntern correspondiente a cada boton
    
    private void _loadEspecialidad() {
        gui.loadEspecialidad(FrmEspecialidades.id, true);
    }

    private void _loadPacientes() {
        gui.loadPacientes(FrmPacientes.id, true);
    }
    
    private void _loadSetAdmin() {
        gui.SetAdmin(FrmSetAdmin.id, true);
    }

    private void _loadObrasocial() {
        gui.loadObraSocial(FrmObraSocial.id, true);
    }
    
    public void _loadSetting() {
        gui.loadSetting(FrmSetting.id, true);
    }
    
    public void _loadCargos() {
        gui.loadCargos(FrmCargos.id, true);
    }
    
    public void _loadHorarios() {
        gui.loadHorarios(FrmHorarios.id, true);
    }
    
    public void _loadProf_Esp() {
        gui.loadProf_Esp(FrmProfEsp.id, true);
    }
    
    private void _loadProfesionales() {
        gui.loadProfesionales(FrmProfesionales.id, true);
    }
    
    private void _loadPersonales() {
        gui.loadPersonales(FrmPersonales.id, true);
    }
    
    private void _loadTurnos() {
        gui.loadTurno(FrmTurnos.id, true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBarButtons = new javax.swing.JToolBar();
        btnAdministrador = new botones.BtnAdministrador();
        btnDatabase = new botones.BtnDatabase();
        btnProfesionales = new botones.BtnProfesionales();
        btnPersonales = new botones.BtnPersonal();
        btnPacientes = new botones.BtnPacientes();
        btnCargos = new botones.BtnCargos();
        btnEspecialidades = new botones.BtnEspecialidades();
        btnTurno = new botones.BtnTurno();
        btnHorarios = new botones.BtnHorario();
        btnObrasSociales = new botones.BtnObrasocial();
        btnEspProfesionales = new botones.BtnProfEsp();
        jDesktopIntern1 = new miselaneos.JDesktopIntern();

        setTitle("ADMINISTRADOR");
        getContentPane().setLayout(new java.awt.BorderLayout());

        jToolBarButtons.setBorder(null);
        jToolBarButtons.setForeground(new java.awt.Color(153, 153, 153));
        jToolBarButtons.setRollover(true);

        btnAdministrador.setFocusable(false);
        btnAdministrador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdministrador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradorActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnAdministrador);

        btnDatabase.setFocusable(false);
        btnDatabase.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDatabase.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatabaseActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnDatabase);

        btnProfesionales.setFocusable(false);
        btnProfesionales.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProfesionales.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProfesionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfesionalesActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnProfesionales);

        btnPersonales.setFocusable(false);
        btnPersonales.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPersonales.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPersonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalesActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnPersonales);

        btnPacientes.setFocusable(false);
        btnPacientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPacientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacientesActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnPacientes);

        btnCargos.setFocusable(false);
        btnCargos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCargos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargosActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnCargos);

        btnEspecialidades.setFocusable(false);
        btnEspecialidades.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEspecialidades.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspecialidadesActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnEspecialidades);

        btnTurno.setFocusable(false);
        btnTurno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTurno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnoActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnTurno);

        btnHorarios.setFocusable(false);
        btnHorarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHorarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorariosActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnHorarios);

        btnObrasSociales.setText("Obras Sociales");
        btnObrasSociales.setFocusable(false);
        btnObrasSociales.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnObrasSociales.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnObrasSociales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrasSocialesActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnObrasSociales);

        btnEspProfesionales.setFocusable(false);
        btnEspProfesionales.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEspProfesionales.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEspProfesionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspProfesionalesActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnEspProfesionales);

        getContentPane().add(jToolBarButtons, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(jDesktopIntern1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspecialidadesActionPerformed
        _loadEspecialidad();
    }//GEN-LAST:event_btnEspecialidadesActionPerformed

    private void btnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientesActionPerformed
        _loadPacientes();
    }//GEN-LAST:event_btnPacientesActionPerformed

    private void btnObrasSocialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrasSocialesActionPerformed
        _loadObrasocial();
    }//GEN-LAST:event_btnObrasSocialesActionPerformed

    private void btnCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargosActionPerformed
        _loadCargos();
    }//GEN-LAST:event_btnCargosActionPerformed

    private void btnDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatabaseActionPerformed
        _loadSetting();
    }//GEN-LAST:event_btnDatabaseActionPerformed

    private void btnPersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalesActionPerformed
        _loadPersonales();
    }//GEN-LAST:event_btnPersonalesActionPerformed

    private void btnProfesionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesionalesActionPerformed
        _loadProfesionales();
    }//GEN-LAST:event_btnProfesionalesActionPerformed

    private void btnTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnoActionPerformed
        _loadTurnos();
    }//GEN-LAST:event_btnTurnoActionPerformed

    private void btnHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorariosActionPerformed
        _loadHorarios();
    }//GEN-LAST:event_btnHorariosActionPerformed

    private void btnEspProfesionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspProfesionalesActionPerformed
        _loadProf_Esp();
    }//GEN-LAST:event_btnEspProfesionalesActionPerformed

    private void btnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradorActionPerformed
        _loadSetAdmin();
    }//GEN-LAST:event_btnAdministradorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private botones.BtnAdministrador btnAdministrador;
    private botones.BtnCargos btnCargos;
    private botones.BtnDatabase btnDatabase;
    private botones.BtnProfEsp btnEspProfesionales;
    private botones.BtnEspecialidades btnEspecialidades;
    private botones.BtnHorario btnHorarios;
    private botones.BtnObrasocial btnObrasSociales;
    private botones.BtnPacientes btnPacientes;
    private botones.BtnPersonal btnPersonales;
    private botones.BtnProfesionales btnProfesionales;
    private botones.BtnTurno btnTurno;
    private miselaneos.JDesktopIntern jDesktopIntern1;
    private javax.swing.JToolBar jToolBarButtons;
    // End of variables declaration//GEN-END:variables
}