/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package forms.personal;

import forms.pacientes.FrmPacientes;
import forms.turnos.FrmTurnos;
import java.beans.PropertyVetoException;
import miselaneos.Fecha;
import miselaneos.FrmIntern;
import miselaneos.GUI;
import miselaneos.Iconos;
import miselaneos.Imagenes;

/**
 *
 * @author cesar
 */
public class FrmPersonal extends FrmIntern {
    public static int id = 8;

    
    public static Iconos iconos = new Iconos();//Declaro public y static para poder acceder luego desde cualquier lugar del proyecto en cualquier objeto
    public static Imagenes imgs = new Imagenes(); //Misma situacion que Iconos
    public static Fecha fe = new Fecha(); //Misma situacion que Iconos
    
    private GUI gui;
    /**
     * Creates new form FrmPersonal
     */
    public FrmPersonal() {
        gui = new GUI();
        initComponents();
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException e) {
            e.printStackTrace();
        }
    }
    
    private void _loadPacientes() {
        gui.loadPacientes(FrmPacientes.id, true);
    }
    
    private void _loadTurnos() {
        gui.loadTurno(FrmTurnos.id, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBarButtons = new javax.swing.JToolBar();
        btnPacientes = new botones.BtnPacientes();
        btnTurno = new botones.BtnTurno();
        jDesktopIntern1 = new miselaneos.JDesktopIntern();

        setTitle("Secretaría");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jToolBarButtons.setForeground(new java.awt.Color(153, 153, 153));
        jToolBarButtons.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBarButtons.setAlignmentY(0.3F);
        jToolBarButtons.setBorderPainted(false);

        btnPacientes.setText(" Registrar Pacientes ");
        btnPacientes.setAlignmentX(0.5F);
        btnPacientes.setFocusable(false);
        btnPacientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPacientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacientesActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnPacientes);

        btnTurno.setText("  Agendar Turnos   ");
        btnTurno.setAlignmentX(0.5F);
        btnTurno.setFocusable(false);
        btnTurno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTurno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnoActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnTurno);

        getContentPane().add(jToolBarButtons);
        getContentPane().add(jDesktopIntern1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientesActionPerformed
        _loadPacientes();
    }//GEN-LAST:event_btnPacientesActionPerformed

    private void btnTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnoActionPerformed
        _loadTurnos();
    }//GEN-LAST:event_btnTurnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private botones.BtnPacientes btnPacientes;
    private botones.BtnTurno btnTurno;
    private miselaneos.JDesktopIntern jDesktopIntern1;
    private javax.swing.JToolBar jToolBarButtons;
    // End of variables declaration//GEN-END:variables
}
